version: "3.9"
services:
  failing:
    image: docker.pkg.github.com/rubenrubens/cq-testing/cq
    volumes:
    - .:/testing
    command: bash failing.sh
  passing:
    image: docker.pkg.github.com/rubenrubens/cq-testing/cq
    volumes:
    - .:/testing
    command: bash passing.sh
