version: "3.9"
services:
  failing:
    image: ghcr.io/rubenrubens/cq-conda
    volumes:
    - .:/cadquery:z
    command: bash failing.sh
  passing:
    image: ghcr.io/rubenrubens/cq-conda
    volumes:
    - .:/cadquery:z
    command: bash passing.sh
  single_test:
    image: ghcr.io/rubenrubens/cq-conda
    volumes:
    - .:/cadquery:z
    command: bash single_test.sh
