version: "3.9"
services:
  all:
    image: docker.pkg.github.com/rubenrubens/cq-testing/cq
    volumes:
    - .:/testing
    command: bash run-all-tests.sh
  passing:
    image: docker.pkg.github.com/rubenrubens/cq-testing/cq
    volumes:
    - .:/testing
    command: bash run-passing-tests.sh
