version: "3.9"
services:
  failing:
    image: ghcr.io/rubenrubens/cq-testing:demo
    volumes:
    - .:/testing:z
    command: bash failing.sh
  passing:
    image: ghcr.io/rubenrubens/cq-testing:demo
    volumes:
    - .:/testing:z
    command: bash passing.sh
