name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  passing-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate in docker
        run: docker login docker.pkg.github.com -u RubenRubens -p ${{ secrets.DockerToken }}

      - name: Tests 🧪
        run: docker-compose run passing

  all-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate in docker
        run: docker login docker.pkg.github.com -u RubenRubens -p ${{ secrets.DockerToken }}

      - name: Tests 🧪
        run: docker-compose run all
